defaultNetwork: 'testnet'
networks:
  [
    { name: 'mainnet', consensusNodes: [] },
    { name: 'previewnet', consensusNodes: [] },
    { name: 'testnet', consensusNodes: [] },
  ]
accounts:
  [
    {
      accountId: '',
      privateKey: { key: '', type: '' },
      network: '',
      alias: '',
      importedTokens: [],
    },
  ]
logs:
  path: './logs'
  level: 'ERROR'
factories: [{ id: '', network: '' }]
