name: CLI Publish NPM
on: 
  workflow_dispatch:
  push:
    branches: [npm-gitflow-sprint15]
defaults:
  run:
    working-directory: cli
jobs:
  ALL-publish:
    name: Publish ALL packages
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Use Node.js TLS 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/101730247931/locations/global/workloadIdentityPools/registry-identity-pool/providers/gh-provider'
          service_account: 'stablecoin-npm-publisher@hedera-registry.iam.gserviceaccount.com'
          token_format: 'access_token'
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Create .npmrc
        run: |
          cat << EOF > .npmrc
            @hashgraph:registry=https://us-npm.pkg.dev/hedera-registry/stablecoin-npm/
            //us-npm.pkg.dev/hedera-registry/stablecoin-npm/:_authToken="${{ steps.auth.outputs.access_token }}"
            //us-npm.pkg.dev/hedera-registry/stablecoin-npm/:always-auth=true
          EOF 
      - name: Install contracts dependencies 
        run: npm run install:contracts
      - name: Publish contracts package
        run: npm run publish:contracts
      - name: Install sdk dependencies 
        run: npm run install:sdk
      - name: Publish sdk package
        run: npm run publish:sdk
      - name: Install cli dependencies 
        run: npm run install:cli
      - name: Publish cli package
        run: npm run publish:cli
      - name: Install web dependencies 
        run: npm run install:web
      - name: Publish web package
        run: npm run publish:web
