name: CLI Publish NPM
on:
  workflow_dispatch:
  push:
    branches: [not-main]
    paths:
      - 'cli/**'
defaults:
  run:
    working-directory: cli
jobs:
  test-node:
    name: Publish CLI package
    needs: [CLI - Test]
    runs-on: [ self-hosted, Linux, medium, ephemeral ]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Use Node.js TLS 16.x
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 18
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/101730247931/locations/global/workloadIdentityPools/registry-identity-pool/providers/gh-provider'
          service_account: 'stablecoin-npm-publisher@hedera-registry.iam.gserviceaccount.com'
          token_format: 'access_token'
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Create .npmrc
        run: |
          cat << EOF > .npmrc
            @hashgraph:registry=https://us-npm.pkg.dev/hedera-registry/stablecoin-npm/
            //us-npm.pkg.dev/hedera-registry/stablecoin-npm/:_authToken="${{ steps.auth.outputs.access_token }}"
            //us-npm.pkg.dev/hedera-registry/stablecoin-npm/:always-auth=true
          EOF
      - name: Publish CLI package
        run: npm publish
