name: CI
on: push

jobs:
    compile:
        name: Compile site assets
        runs-on: ubuntu-latest
        steps:
              - uses: actions/checkout@v3
              - name: Use Node.js TLS 16.x
                uses: actions/setup-node@v1
                with:
                  node-version: 16.x
              - name: "Set up environment"
                run: docker build -t rpc ./dockerfile
              - name: "Wait for docker to finish building"
                run: sleep 10
              - name: "Upload  server"
                run: docker run rpc >output.log 2>&1 &
              - name: "Wait for to rpc to start"
                run: sleep 10
              - name: Install dependencies Hashconnect
                run: npm install
                working-directory: hashconnect/lib
              - name: Build Hashconnect
                run: npm run build
                working-directory: hashconnect/lib
              - name: Install dependencies Contracts
                run: npm install
                working-directory: contracts
              - name: Install dependencies SDK
                run: npm install
                working-directory: sdk
              - name: Install Jest                
                run: npm install --save-dev jest
              - name: Test
                run : npm  install
                working-directory: cli
              - name: Test
                run : npm run test
                working-directory: cli
              - name: "Wait for to rpc to start"
                run: docker stop rpc
                        